const nameArr = [
  "Phenosandra XI",
  "Cyclovelu",
  "Pagozine - V9",
  "Jesma",
  "Josive - V2",
  "Gran - Zobyte",
  "Gyrodia 7",
  "Technoxadon",
  "Shadoxis",
  "M - reo",
  "Nesect",
  "Omniticon",
  "Tite - V9",
  "Copernilus",
  "Uranoda X",
  "Myrorgonon",
  "Sigmadon",
  "Rianon XV",
  "Exerron",
  "Rasect",
  "Dutalia",
  "Optimolinix 9",
  "Linosmitter",
  "Primosizor",
  "Memostavo",
  "Intermbix 5",
  "Abopso",
  "Artethya",
  "Diamani XII",
  "Pyrenack 9",
  "Elxil XI",
  "Pexigene 8",
  "Antico",
  "Rivemonico - Li",
  "Eleraxi",
  "Monodroid VIII",
  "Manastar",
  "Fuplex X",
  "Compusator",
  "Devacoptor 7",
  "Gucepra",
  "Bophaliv",
  "Adrore",
  "Zedruna",
  "Yipra",
  "Loiruta",
  "Phathalara",
  "Couruta",
  "Drapus K43D",
  "Tronoe 3RVI",
  "Bostrohines",
  "Rannaurilia",
  "Zillade",
  "Mustriea",
  "Xenope",
  "Cetera",
  "Grakunides",
  "Vigaphus",
  "Crars Z51G",
  "Dradus 9781",
  "Chimabos",
  "Vannehines",
  "Lunrion",
  "Rogov",
  "Duagawa",
  "Kueyama",
  "Businope",
  "Cenithea",
  "Therth 913E",
  "Dichi 7417",
  "Tanremia",
  "Vuphuahines",
  "Ocars",
  "Ostromia",
  "Beinerth",
  "Counus",
  "Chogiliv",
  "Zidonus",
  "Tryke 13Y6",
  "Thypso 109",
  "Rugriastea",
  "Cigeurilia",
  "Zaccars",
  "Aphosie",
  "Zinus",
  "Tuhines",
  "Phaabos",
  "Chotinia",
  "Drilia 99VJ",
  "Chars 280G",
  "Abagawa",
  "Codouturn",
  "Xangov",
  "Tagrillon",
  "Malia",
  "Uwei",
  "Curinides",
  "Suophus",
  "Nosie WU",
  "Zeon 7E",
  "Bisunope",
  "Thusoumia",
  "Huborth",
  "Henrichi",
  "Poimia",
  "Iovis",
  "Droupra",
  "Crikilara",
  "Vyria M8",
  "Gara U8",
  "Dunnuatania",
  "Ebratune",
  "Cogruna",
  "Aveon",
  "Eiruta",
  "Ielea",
  "Cuzinope",
  "Thoetov",
  "Lilia 95E",
  "Billes H44",
  "Kazoinus",
  "Tugniutis",
  "Dichides",
  "Sogriri",
  "Tharus",
  "Kecury",
  "Greilea",
  "Chuehiri",
  "Phion MI4S",
  "Bade 471",
  "Egnaclite",
  "Hubroalara",
  "Gudriea",
  "Venrolla",
  "Binope",
  "Kilea",
  "Chexaruta",
  "Caoruta",
  "Bosie OB1",
  "Bore 4W1",
  "Daphuirus",
  "Suphuwei",
  "Senzerth",
  "Zadrosie",
  "Saetera",
  "Ibos",
  "Grukoyama",
  "Nuutov",
  "Losie 631",
  "Llyke 0",
  "Yicrautera",
  "Thibbotera",
  "Docillon",
  "Yollillon",
  "Niutis",
  "Yeiyama",
  "Guthigawa",
  "Chibiter",
  "Sora 93SC",
  "Miuq 28M",
  "Chugiowei",
  "Chephecarro",
  "Tinzora",
  "Hatrone",
  "Yatis",
  "Istea",
  "Zibitune",
  "Briyohines",
  "Vichi QAN",
  "Gyke VXU",
  "Tutheustea",
  "Pitrater",
  "Rugneshan",
  "Cophagua",
  "Gauter",
  "Beawei",
  "Nagehines",
  "Zechetis",
  "Byke SCB8",
  "Silia Z2C",
  "Thizelara",
  "Odroitera",
  "Roccagua",
  "Dalnara",
  "Vaugantu",
  "Lahiri",
  "Thohewei",
  "Vupagantu",
  "Nars L5S",
  "Zone 0PWH",
  "Yozoiter",
  "Punnunides",
  "Monkippe",
  "Rengapus",
  "Veonov",
  "Daozuno",
  "Creoturn",
  "Loitov",
  "Phillon 92M",
  "Stroria 730",
];

const randomName = Math.floor(Math.random() * nameArr.length);

export default () => nameArr[randomName];
