export default {
  RIGHT: [1],
  LEFT: [2],
  CEILING: [3],
  FLOOR: [4],
  TL_INNER: [6],
  TR_INNER: [5],
  BR_INNER: [7],
  BL_INNER: [8],
  TL_OUTER: [9],
  TR_OUTER: [10],
  BL_OUTER: [11],
  BR_OUTER: [12],
  LEDGE_L: [13],
  LEDGE_M: [14],
  LEDGE_R: [15],
  ROCK: [16],
  POLE_UP: [17],
  POLE_DOWN: [18],
  POLE_M: [19],
  ENCLOSED: [24],
} as { [key: string]: Array<number> };
