export default {
  RIGHT: [1,2],
  LEFT: [3,4],
  CEILING: [5],
  FLOOR: [6,7,8],
  TR_INNER: [9],
  TL_INNER: [10],
  BR_INNER: [11],
  BL_INNER: [12],
  TL_OUTER: [13],
  TR_OUTER: [14],
  BL_OUTER: [15],
  BR_OUTER: [16],
  LEDGE_L: [17],
  LEDGE_M: [18],
  LEDGE_R: [19],
  ROCK: [20],
  POLE_UP: [21],
  POLE_DOWN: [22],
  POLE_M: [23],
  ENCLOSED: [29],
} as { [key: string]: Array<number> };